/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package HO5;

import HO5.RLE.Huffman;
import HO5.RLE.IRLE;
import HO5.RLE.RLEAlgo1;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        // System.out.println(new App().getGreeting());
        String in = cnc(4, 'a') + cnc(6, 'b') + cnc(3, 'c') + cnc(15, 'e') + cnc(26, 'f');

        System.out.printf("First algorithm,  %s\n", compress(in, new RLEAlgo1())); 

        System.out.println("Input: milch_macht_munter");
        System.out.printf("Encoded: %s\n", Huffman.compress("milch_macht_munter"));
    }

    static String compress (String in, IRLE algo) {

        return algo.compress(in);
    }
    
    static String cnc (int n, char c) {

        String result = new String();
        for (int i = 0; i < n; i++) {
            result += c;
        }

        return result;
    }

}
